apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss13793-inference-deployment
  labels:
    app: inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
    spec:
      containers:
      - name: ss13793-inference-container
        imagePullPolicy: Always
        image: blackcaesaris/inferenceimage
        env:
        - name: MODEL_SAVE_PATH
          value: "/ss13793-mount/ss13793_model.pth"
        ports:
        - containerPort: 80
          name: infer-port
        volumeMounts:
        - name: ss13793-volume
          mountPath: /ss13793-mount
      volumes:
      - name: ss13793-volume
        persistentVolumeClaim:
          claimName: ss13793-pvc