apiVersion: v1
kind: Service
metadata:
  name: ss13793-inference-service
spec:
  selector:
    app.kubernetes.io/name: inference
  ports:
  - name: inference-service-port
    protocol: TCP
    port: 80
    targetPort: inference-container-port