apiVersion: v1
kind: Service
metadata:
  name: ss13793-inference-service
spec:
  selector:
    app: inference
  type: NodePort
  ports:
  - name: inference-service-port
    protocol: TCP
    port: 80
    targetPort: infer-port
    nodePort: 30007